
import random 

# Part 1 - Keeping it Classy
class Product():
    def __init__(self, 
                 name, 
                 price = 10., 
                 weight = 20., 
                 flammability = 0.5, 
#                  identifier
                ):
        # ususally in a system GUID/UUID can be either generated by a function,
        # or manually input by user. if generated by GUID/UUID function, we
        # won't need to check whether it is unique; if input by user, we will
        # have to check whether it has already existed in the system.
        # random from 1000000 to 9999999, includisve
        self.identifier = random.randint(1000000, 9999999)
        self.name = name
        self.price = price
        self.weight = weight
        self.flammability = flammability
    
    def stealability(self):
        steal = self.price / self.weight
        if steal < 0.5:
            return "Not so stealable..."
        elif (steal >= 0.5) and (steal < 1.0):
            return "Kinda stealable."
        else:
            return "Very stealable!"
    
    def explode(self):
        expl = (self.flammability * self.weight)
        if expl < 10:
            return "...fizzle."
        elif (expl >= 10) and (expl < 50):
            return "...boom!"
        else:
            return "...BABOOM!!"
    
class BoxingGlove(Product):
    def __init__(self, name):
        super().__init__(name, weight=10)
  
    def explode(self):
        return "...it's a glove."
  
    def punch(self):
        if self.weight < 5:
            return "That tickles."
        elif self.weight >= 5 and self.weight < 15:
            return "Hey that hurt!"
        else:
            return "OUCH!"